### ISSUE TITLE
Make this more multilingual friendly

### ISSUE THREAD

**Issue by ruisilva450** [koss-lebedev/bootstrap-duration-picker#10]
Hi, 
I wanted to be able to change language.
Do you accept PR? 
I'm thinking of enabling a way to pass an object with the translations or use momentJS to take care of this.

**Comment by koss-lebedev** [comment]
Hi there, 

yes, feel free to file a PR. It may be a good idea to allow to set `lang` option to either string or an object. So, when users set `lang` option to a string (like `en`, for instance), we'll use internal `langs` object for fetching translations, as it's working now. If users set `lang` option to an object, we'll get translations directly from it, ignoring internal `langs` object. This way we can extend current API without breaking it.
