### ISSUE TITLE
Respect ngModel value on init

### ISSUE THREAD

**Issue by ruisilva450** [koss-lebedev/bootstrap-duration-picker#11]
Hi,

When I initialize, the ngModel is ignored and it puts the value to 0

You should read the value in ngModel and do the reverse calculation to fill the inputs

**Comment by koss-lebedev** [comment]
This is not AngularJS plugin, so `ngModel` doesn't make sense in its context. If you need to set the initial value, set the value of the HTML input to which plugin will be applied before you call `.durationPicker()`
