### ISSUE TITLE
Reset value

### ISSUE THREAD

**Issue by Nittarab** [koss-lebedev/bootstrap-duration-picker#13]
Hi, first of all thanks for this plugin!

I have a problem, how can i reset to 0  all the values?
I use the  `.reset()` function to reset all the form fields and the value of the duration picker input field go to 0, but is not update the `#bdp-hours` value...

**Comment by koss-lebedev** [comment]
Hi @Nittarab , you can use `setValue` method like this:

    $('#your-selector').data('durationPicker').setValue(0);

Make sure that you have the lastest version, I added that method in v.2.1.1
