### ISSUE TITLE
setValue is not a function

### ISSUE THREAD

**Issue by audas** [koss-lebedev/bootstrap-duration-picker#17]
I can access the picker with $("picker").data("durationPicker") however when using $("picker").data("durationPicker").setValue(1)  it fails with is not a function ?

**Comment by audas** [comment]
Ok - not sure whats going on - values need to be enclosed in quotes. 

??

**Comment by koss-lebedev** [comment]
can you check the example in `demo` folder to see if you do something different? Maybe you're trying to call setValue before initializing the plugin?

**Comment by audas** [comment]
I had to call a second function setting the values after the picker was initialised.  Tracing out the Object showed it existed - however I could not call it within the same function.

I passed the values to a second function and set them.

**Comment by koss-lebedev** [comment]
OK, I'm glad you figured this out. I'll close this issue then

**Comment by JackHarrison** [comment]
I'm having the same issue. I have created the duration picker and can also see it's initialised however when I use your example to setValue I get 'Cannot read property 'setValue' of undefined'. I have replaced the selector name with the id of the object in the dom that I am trying to set.
