### ISSUE TITLE
How do we make the popover disappear without clicking the durationpicker field again?

### ISSUE THREAD

**Issue by pcatattacks** [koss-lebedev/bootstrap-duration-picker#6]
![image](https://cloud.githubusercontent.com/assets/22510675/22801627/383e07aa-eed3-11e6-8d29-1f4cf81691f6.png)

In the image above, our cursor is in the tags field, but the popover still hasn't disappeared.

**Comment by koss-lebedev** [comment]
Duration picker uses standard bootstrap popover component, so you can use the same trick you'd use to hide bootstrap popover

Something like this -http://stackoverflow.com/questions/20466903/bootstrap-popover-hide-on-click-outside
